import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { ChatThreadDeepLink } from "@/components/chat-thread-deep-link";
import { FloatingChatBubbleServer } from "@/components/floating-chat-bubble-server";
import { SignedInNavLinks } from "@/components/signed-in-nav-links";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ChatThreadDeepLink />
        <SignedInNavLinks />
        {children}
        <FloatingChatBubbleServer />
      </body>
    </html>
  );
}
